apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  labels:
    name: worker-app-pod
    app: demo-voting-app
spec:
  containers:
  - name: worker-app
    image: kodekloud/examplevotingapp_worker:v1
# apiVersion: v1
# kind: Pod
# metadata:
#   name: worker-app-pod
#   labels:
#     name: worker-app-pod
#     app: demo-voting-app
# spec:
#   containers:
#   - name: worker-app
#     image: kodekloud/examplevotingapp_worker:v1
#     env: 
#       - name: DATABASE_HOST
#         value: "postgres-service"  # Replace with your PostgreSQL service name
#       - name: DATABASE_PORT
#         value: "5432"               # Default PostgreSQL port
#       - name: POSTGRES_NAME
#         value: "postgres"           # Your PostgreSQL username
#       - name: POSTGRES_PASSWORD
#         value: "postgres"           # Your PostgreSQL password
#       - name: DATABASE_NAME
#         value: "postgres"         # Replace with your PostgreSQL database name

